version: "3"
services:
  code-server:
    image: ramadhanifajar07/serverganteng:latest
    container_name: code-server
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Jakarta
      - PASSWORD=
      - SUDO_PASSWORD=
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
